name       : cinnamon-translations
version    : 5.8.1
release    : 2
source     :
    - https://github.com/linuxmint/cinnamon-translations/archive/refs/tags/5.8.1.tar.gz : 1cfd2065386bf444841f7818e833d9aadb19706a7dee5c3902b4e13b3d6a3851
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Translation files for the Cinnamon desktop
description: |
    The package contains the translation files for all the Cinnamon packages.
setup      : |
    %patch -p1 < $pkgfiles/0001-Add-install-prefix-and-only-compile-nemo-translation.patch
install    : |
    %make DESTDIR=$installdir
