name       : cinnamon-translations
version    : 5.6.1
release    : 1
source     :
    - https://github.com/linuxmint/cinnamon-translations/archive/refs/tags/5.6.1.tar.gz : afa90bc02e36d9c3d9bddc25a85d7424d15004c448eefecee2471be160cac0fc
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Translation files for the Cinnamon desktop
description: |
    The package contains the translation files for all the Cinnamon packages.
setup      : |
    %patch -p1 < $pkgfiles/0001-Add-install-prefix-and-only-compile-nemo-translation.patch
install    : |
    %make DESTDIR=$installdir
